server:
  port: 8080

spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: product_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/products/**

        - id: store_route
          uri: http://localhost:8082
          predicates:
            - Path=/api/stores/**

        - id: cart_route
          uri: http://localhost:8083
          predicates:
            - Path=/api/cart/**

        - id: shipping_route
          uri: http://localhost:8084
          predicates:
            - Path=/api/shipping/**

        - id: transaction_route
          uri: http://localhost:8085
          predicates:
            - Path=/api/transaction/**

  data:
    mongodb:
      uri: mongodb+srv://672021019:trwebservice@trcluster.f0qe8vj.mongodb.net/
      database: desktop-app

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.cloud.gateway: DEBUG
# Additional application-specific configurations can be added here
